library(NicheMapR)

ectoR_input <- list(
  Ww_g = 40,
  alpha = 0.85,
  epsilon = 0.95,
  rho_body = 1000,
  fatosk = 0.4,
  fatosb = 0.4,
  shape = 3,
  shape_a = 1,
  shape_b = 3,
  shape_c = 2 / 3,
  conv_enhance = 1,
  custom_shape = c(10.4713, 0.688, 0.425, 0.85, 3.798, 0.683, 0.694, 0.743),
  pct_cond = 10,
  pct_touch = 0,
  postur = 1,
  orient = 0,
  k_flesh = 0.5,
  M_1 = 0.013,
  M_2 = 0.8,
  M_3 = 0.038,
  M_4 = 0,
  Q_act = 0,
  pct_wet = 0.1,
  pct_eyes = 0,
  pct_mouth = 0,
  psi_body = -707,
  pantmax = 1,
  F_O2 = 20,
  RQ = 0.8,
  delta_air = 0.1,
  leaf = 0,
  g_vs_ab = 0.3,
  g_vs_ad = 0,
  elev = 0,
  alpha_sub = 0.8,
  epsilon_sub = 1,
  epsilon_sky = 1,
  pres = 101325,
  fluid = 0,
  O2gas = 20.95,
  CO2gas = 0.03,
  N2gas = 79.02,
  K_sub = 0.5,
  PDIF = 0.1,
  SHADE = 10,
  QSOLR = 1000,
  Z = 20,
  TA = 20,
  TGRD = 30,
  TSUBST = 30,
  TSKY = -5,
  VEL = 1,
  RH = 5
)

ectoR_output <- ectoR_devel(
  Ww_g = ectoR_input$Ww_g,
  alpha = ectoR_input$alpha,
  epsilon = ectoR_input$epsilon,
  rho_body = ectoR_input$rho_body,
  fatosk = ectoR_input$fatosk,
  fatosb = ectoR_input$fatosb,
  shape = ectoR_input$shape,
  shape_a = ectoR_input$shape_a,
  shape_b = ectoR_input$shape_b,
  shape_c = ectoR_input$shape_c,
  conv_enhance = ectoR_input$conv_enhance,
  custom_shape = ectoR_input$custom_shape,
  pct_cond = ectoR_input$pct_cond,
  pct_touch = ectoR_input$pct_touch,
  postur = ectoR_input$postur,
  orient = ectoR_input$orient,
  k_flesh = ectoR_input$k_flesh,
  M_1 = ectoR_input$M_1,
  M_2 = ectoR_input$M_2,
  M_3 = ectoR_input$M_3,
  M_4 = ectoR_input$M_4,
  Q_act = ectoR_input$Q_act,
  pct_wet = ectoR_input$pct_wet,
  pct_eyes = ectoR_input$pct_eyes,
  pct_mouth = ectoR_input$pct_mouth,
  psi_body = ectoR_input$psi_body,
  pantmax = ectoR_input$pantmax,
  F_O2 = ectoR_input$F_O2,
  RQ = ectoR_input$RQ,
  delta_air = ectoR_input$delta_air,
  leaf = ectoR_input$leaf,
  g_vs_ab = ectoR_input$g_vs_ab,
  g_vs_ad = ectoR_input$g_vs_ad,
  elev = ectoR_input$elev,
  alpha_sub = ectoR_input$alpha_sub,
  epsilon_sub = ectoR_input$epsilon_sub,
  epsilon_sky = ectoR_input$epsilon_sky,
  pres = ectoR_input$pres,
  fluid = ectoR_input$fluid,
  O2gas = ectoR_input$O2gas,
  CO2gas = ectoR_input$CO2gas,
  N2gas = ectoR_input$N2gas,
  K_sub = ectoR_input$K_sub,
  PDIF = ectoR_input$PDIF,
  SHADE = ectoR_input$SHADE,
  QSOLR = ectoR_input$QSOLR,
  Z = ectoR_input$Z,
  TA = ectoR_input$TA,
  TGRD = ectoR_input$TGRD,
  TSUBST = ectoR_input$TSUBST,
  TSKY = ectoR_input$TSKY,
  VEL = ectoR_input$VEL,
  RH = ectoR_input$RH
)
write.csv(unlist(ectoR_input), file = '../data/ectoR_input.csv')
write.csv(unlist(ectoR_output), file = '../data/ectoR_output.csv')
# return body temperature
ectoR_output$TC
# return skin temperature
ectoR_output$TS
# return heat budget
ectoR_output$enbal
# return O2 consumption rate and water loss
ectoR_output$masbal
